"""Banshee window icon embedded as a base64 PNG, so the app needs no external image file."""

import base64

_ICON_PNG_BASE64 = (
    "iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAYAAAD0eNT6AAAQfklEQVR4nO3dW5LiWLJAUVGWk2VEDFf1UYkVEQEEiPNwP77W17W2"
    "vplKoPEtl4BtAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADo4jT7AID59n3fR/+dp9PJ"
    "+w9M9M/sAwAAxhMAAFCQAACAggQAFDfj+j8wnwAAgIIEAAAUJAAAoCABAIW5/g91CQBgCvEBcwkAKMoAhtoEAAAUJACgIGf/gAAA"
    "gIIEABTT8uz/dLm0+qOAwf7MPgCgjYxr/X3fdz8LDHPYAABAQQIAAAoSAMAhrv9DbgIAAAoSAABQkAAApsr46QVYgQAA3ub6P+Qn"
    "AICPiAHISQDAAkau0Q18WIMAAICCBAAk5+wfOEIAAEBBAgB4Sc+zfx8FhPEEACTWYnC+Mth/+++4NAD5CAAobj+fZx8CMIEAAJ6e"
    "wTu7hzUJAEiq1XVzAx5qEgAAUJAAAB6yHYB1CQCgiU9jwUcBYSwBAGzb5mwfqhEAwF2CANYmAKAwQx7q+jP7AIDnXBsHerABgKLu"
    "nf3bCEAdAgAAChIAwA9HNwE2CJCHAICCDGpAAABfzIwDNzzCOAIAAAoSABBYjzNi639g2wQAAJQkAACgIAEANOUSA+QgACAod8QD"
    "PQkAAChIAABAQQIAFpX1x35c+oAxBAAAFCQAAKAgAQALy7Dyv8dlAOhPAABAQQIAFjdjC5B18wCVCAAAKEgAwIJWOAN3HwD0JQCg"
    "gBWCAGhLAABAQQIAirAFAG4JAFjMSoPefQDQjwAAgIIEAAAUJACALla6FAErEgAAUJAAgIDc/Ab0JgCAblpcBhBD0IcAAICCBAAA"
    "FCQAAKAgAQB05eOAEJMAAICCBAAAFCQAYDH7+Tz7EIAEBADQnfsAIB4BAITny4CgPQEAAAUJAAAoSADAgtwICPxGAMBC3GwHvEoA"
    "AEOIE4hFAMBiDFrgFQIAFnJ77d99AMAzAgAWZAsA/EYAAEBBAgAWtdoWwLcBQlsCABay2tAH+hEAAFCQAACAggQAMIxLFBCHAACA"
    "ggQAABQkAIA0fBQQ2hEAAFCQAICF+P5/4FUCAAAKEgAAUJAAAICCBAAAFCQAgKF8GyDEIAAAoCABAAAFCQAAKEgAAEBBAgAAChIA"
    "sBhfBwy8QgAAw/koIMwnAIDhPtlS+ElgaEMAQECn0+k0+xiAtQkAYDiXAGA+AQAABQkAAChIAMCCfBQQ+I0AAICCBAAAFCQAAKAg"
    "AQCk48uA4HMCABblRkDgGQEAAAUJAAjK1wEDPQkAICX3AcBnBAAwhd8DgLkEAAAU9Gf2AQAc9c5lAPdUwFc2AEAJ+1+zjwOisAEA"
    "SvkkAmwRWIkNAARm4MRii8BKBAAAFCQAAN5kC8AKBADAASKA7AQAMI0vA4J5BAAE50ZAoAcfA6SLGevRVQelVXNc+77vq77uWJ8N"
    "AMswKAFeJwBYyn5j9rHwGvcBwBwCgGUJAYDHBADLEwEAP7kJEAjr3uWB/XyecCSwHhsASrAFiO3eoH90b8DpcnHfADRgA0AZGT+y"
    "JVweO10uT7cBzyLBFgEEAMVkjAAeO7oJuP7/CQEqcwmAcpxVAwgAIKCe1/hvz/rdS0BlAoCSMmwBMhxjSyOG8XX4iwBwDwCwsGfX"
    "+Pfz2fCnNAFAWW4IjOfoQD56M58IoDJvfnRxdH3920e7eokWAi3W/6sPtpavk09ed9FeO/Aq9wAQijMyfrOfzz6+Bw24BEA43yNg"
    "xJv99Yw7wtlctZv/XmXoQ1vT3+xYU48V9sgBMDMEWgXAKpuU6IM/QjTCEV64dNFriM0aBqPe5Fue/WcPgOiD/0oAkJV7AAgtyhDY"
    "b8w+lgqiPO+wMgFAeNG+tGX/ZvbxrMbwhzGsrmhuxDXsqEPik3Ww9f9/oj63j7gEQFY2AIT02wCLOuCObgdsEoDRBADhvDrco0bA"
    "LZcKgKh8DwAM8j0CrqtjcQDMYANAKO+e1WfYAjzSazOQ+THZtvzHD1kIAELJdgMYQFYCgPScMa7Hcwr9CQDCObIFOF0uhsZmcAKv"
    "EwAAUJAvsKC5CD9mU/FeghXP/jM8j74IiKxsAAjrkzd/lwR45tTQ7H8LHOXFS3OtP9r2ziDfz+eUXyH8qZVjp8dzZnCDAKCD0Z9t"
    "fzYgqsSAAHifCKA6/wOguRYB8OpAe2c4/PZnZg6ClQNg20QA9ODFT3NHA+DdVf9Rr/w9mWJg9eG/bX2fDxFAVV74NNf7EkDLYdBj"
    "0zBSheF/JQKgLS96msv64zYZY0AAtCEAqMiLnuayBsDVu0N1VhBUGv5XIgDa8YKnuewBcCtqDFQc/tvW//EVAVTixU5zKwXArUgx"
    "UDUAtk0EQCte6DS3agBcHR2+rQZX5eG/bQO3LEKAxXmB09zqAXBrdAxUH/5X0+67EAUsxIuZ5ioFwK1eP15k6N8389MYQoAVeBHT"
    "XNUAuDKwx4jwcUwhQGZevDRXPQBuiYG+RAAc54VLcwLgPjHQXoQAuBICZOMFS3MC4HdioB0RAMd4sdKcAHidEGhDBMD7vFBpTgAc"
    "IwY+EykCtk0IEJ8XKEOJg98JgeNEALzun9kHQC2nAWb/Gz8VbYhxnOAlsvRvlvDICm++tgHvixZQK0Qpa/LCpITMMSAC3hcpAgQA"
    "UXlhUk7GGBAB74sSAQKAqLwwKStbCIiAY2aHgAAgKi9M2PLEgAhoY2QUCACi8sKEb6LHgAhoZ1QIiAAi8qKEByKHgAhoy0aAinwP"
    "ADyw0ncL8NzIoNr/GvYXwgPe2OBNUd68bQH6GH3ToMBkFi88+MDsGBABfYgAKnAJAD7gEsGaRoeVywLM4I0LGhv9Rm4L0NeM7xEQ"
    "lYxgAwCN2QqsZUZg/RaR+2SjHgf6EgDQyagImP1NdxXMioB7w9YAphUBAB2N2gaIgHVFHPgRj4n3CQAYwCWB3GYHVsT1e6Rj4RgB"
    "AIP0joDZQwrIRQDAQDYBrMQWIDcBAIP1jABbgD581PIxEZCXAIAJbALyEQGPRbs/gdd4E4KJer1pGlb92bb8JGxzsQEAOOB0uQgt"
    "UhMAMJEzpvyEAFkJAJisRwRYT48nAshGAAA0YhtAJgIAAnApYC1CgAz+zD4AgFWdLpdQl2O+R0mkY2M8GwAIovUWwJt7DFG2ARGO"
    "gVgEAATiUsC6Ig7giMfEOAIAYJBZ24Bnf6cIqEsAQDC2AOvrGQLf/+yRA97XAefijQYCavVG6uwuh5b3axx9zlsdg4DNwwYAAvIm"
    "WkuEGwVb/f22AHl4k4GgWryRzh4qHHPkbLzlc/3pNkDA5uBJgsA+jQAB8HWYZXs8vg/insff9DKEAEjBkwSB2QJ85tFQq/yY3NP6"
    "OyMEQA7uAQCW9Gyo7eezL0r6y+NQl0qD4D7ZAlQ90313qFV8nHoOfhuAHPwWALCUI4Mt830CRzjrZ9tcAgAW0mKwuTxAFdY0EJxL"
    "AK/putJe8HF0CQBPEiRwNAJWHFz3jD5jX+1x3c/npj9dLABycA8AwJvuDcrMUdBy+JOHSoMEbAAeyzC4Mj0PLR5PG4AcPEmQgAC4"
    "L8PwfyT6c/PJYysAcnAJAILz4yr5RR/2tzJHFe8RAEBKEQZVpsH+qtt/U4THmH4EAJBOlMHU9Ad0gsVElMeYfgQAQAAfXXMP9FPA"
    "5CEAgFQMqJ88Jhzhq4ABoCABAKThTBfaEQAAUJAAAFJw9g9tCQAAKEgAAOE5+4f2BAAUY5j+7/TX7OOAGQQAFJJx+Pc6ZoOf6nwR"
    "EBSQcfD3ZPiDDQAs6/r1sN+Hf7TvnH9GuEA/NgCwKMPzPmf/8B8BAITUI2AeDf+WUbDv+97qz8pIYOUhAAAa+mQAZo4Hgz8fAQCU"
    "kGFAZThG1uEmQCgkyw2A7l+A/gQAsDxn1vCTAABCcfYPYwgAYGnO/uE+AQAABQkAIIzW639n//CYAIAisnwCABhDAABLcvYPzwkA"
    "IAR3/8NYAgBYjrN/+J0AgOBOf80+DmAtAgBYiliC1wgASCDzr8QBMQkAKKDSRwDFErxGAABAQQIAWI4tAPxOAABAQQIAWJItADwn"
    "ACC4KoOs0o2KEIEAAJZVJZ7gCAEAi8t0Zt3jWEUA3CcAAKAgAQAszxYAfhIAQCi9LlmIAPhKAABliAD4nwAAptrP5x//WaYbFyEr"
    "AQALM0h/sgWA/wgACGz1YXU9+x+9BVj9cYVXCACgJBFAdQIACKv3JQwRQGUCAJji3tp/BhFAVQIACG3EjYwigIoEACzKJwDeIwKo"
    "RgAA4Y2KGRFAJQIAGO7I9f+REXDPkL8cBhIAQAhRbgqEKgQAkIb7GqAdAQAM9emZvgiANgQAkI4IgM8JACAM9wHAOAIASMkWAD4j"
    "AGBBmYfjO1uAzP9OmE0AAOHs5/PLISAC4Jg/sw8A4JF7EXBv4J8uF/cPwJtsAIBhWgzpR9sBmwB4jwAAliEC4HUCAEjp0TZBBMBr"
    "BACQlgiA4wQAkJqPDcIxAgAowycF4H8CAEjv3icDvp/tO/uHr3wPALCM/Xz+Muhv/29n//CVDQAwxKgBfG8bYPjDTzYAwJIMfXjO"
    "BgAAChIAAFCQAACAggQAABQkAACgIAEAAAUJAKA7H8mDeAQALMzgBR4RAABQkACARTn7b+d0Op1mHwO0JgBgQdfh7xfwgEcEAMAT"
    "zv5ZlQAAeMDwZ2V+DRDo6tN7EQxh6MMGABbl+j/wjAAAgIIEAAAUJAAAoCABAAAFCQAAKEgAAN34CCDEJQAAoCABAAAFCQAAKEgA"
    "QGCugQO9CAAAKEgAAEBBAgDowkcAITYBAAAFCQBY1Kdn4MDaBAAAFCQAAKAgAQCFjLos4PIDxCcAYGG3g9hQBm4JACAcHwGE/gQA"
    "FODsH/hOAABNiQ3IQQDAwk6Xi4EM3CUAYGGGP/CIAACaERyQhwAAgIIEANBEq7N/HwGEMQQAABQkACC41mfErtMD2yYAAKAkAQAA"
    "BQkAIAw3AMI4AgAKch8AIAAAoCABAHzMRgHyEQBACK7/w1gCAIp6dNbubB5q+DP7AIDf3Ts73vd9b/33GP5Qhw0AFBZl4Fv/w3gC"
    "AAAKEgDAtm3HtwGfbhGc/cMcAgAAChIAkFTPM+co9wYA/QgAwMCHggQAABTk5htIrMd3Adw6XS7P//4GmwM3AcIcNgCQmOEJHCUA"
    "gIfcGwDrEgDANDYYMI8AAA6xHYDcBAAk1/ss2qCHNQkAAChIAMACbAGAdwkA4G2CAPITAMBLWg99nwCAuQQAABQkAACgIAEAAAUJ"
    "AOAtbgCENbgJBwro/auB73IDIMxnAwAABQkAKMAZN/CdAACAggQAMJRtBMQgAKAIgxe4JQAAoCABAIXYAgBXAgAYRoBAHAIAijGE"
    "gW0TAABQkgAAgIIEAAAUJACAIdx7AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB09C/KOwmo6ojfXAAAAABJRU5E"
    "rkJggg=="
)


def icon_bytes():
    return base64.b64decode(_ICON_PNG_BASE64)


def app_icon():
    """Return a QIcon built from the embedded PNG (imports Qt lazily)."""
    from PyQt6.QtGui import QPixmap, QIcon

    pm = QPixmap()
    pm.loadFromData(icon_bytes(), "PNG")
    return QIcon(pm)
